dist: xenial
language: python
cache: pip
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- pytest -v
jobs:
  include:
  - stage: deploy to staging
    deploy:
      provider: heroku
      api_key:
        secure: eG+dFntMzktjSjRfNQZZqAZ0MTMx+0Q8r+JY/QLs+AqObY9aOMIs2isSe45l3fwqPo5nE/OYv9WzOJNL1HzSfQxnmtYNHqLfhzVi0wKXjbd/jZTb6V7f2Gygr8Sh2PKcCTbjssZ/dxqYAzzFRZgsY+Yr8Hk07RvNyfp2mX9zKLCrC6sXYx9YvYNchMSi8A/UFawylu1VnUbo+MBtTPJng4DSos9n0mFbWzpPwL5qSZAE60vYuDaQLVL7SJY66V7Vonc2j79RkWsnCYzalAfQw72ILU8q09chvhlE96vqZMMq9okW4uRlieZBLCaM1Odm/QoKANO5t2gB7aBbR4JTjjoG/99iz5JCLqEoTGlp+XtWW+AqkJyX+NmDCkYtUybVOCrf/k3AlPqpsqmTN8h1eXbSrltp6//CBzJ3UhppUGRWwgg2qKq+AQJ8ZTi4Q+C5shfI/m+8NDj7Pl6Ffoa4luv+yc53v7pDCIYNRbrFhlDOnbKg3OngRXh8+UQ0jlhwUsgwPGVFRZr9bXr8eL9oYV+UvoOCn7wZJGkEc3pA9HanK6qa0xOvcaKrmEnz5kdqJocfFaqBS7tSRsUCKyeP4CTS/n0qzwoQ+Cij83CZ8/PhZUKdbfGftRDEYSO8JT9nfuAwyNmv5ZFxGf1KAoXou3TCpmGdi+12XAEIdCsHuWU=
      app:
        master: system-testing-template
      on:
        repo: sschilbe/SystemTestingTemplate
  - stage: test staging
    install:
    - pip install robotframework
    - pip install --upgrade requests
    - pip install robotframework-selenium2library
    - pip install --upgrade urllib3
    script:
    - robot --variable BROWSER:chrome --variable VERSION:latest --variable PLATFORM:MAC
      test.robot
