dist: xenial
language: python
cache: pip
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- pytest -v
jobs:
  include:
  - stage: deploy to staging
    deploy:
      provider: heroku
      api_key:
        secure: 2na/VvDKU7a3Oyk7UrUKF1EVDJJ/AmV69KaH04/iqcxmv3KsMZ7P58Ln6yY6502ozEX0GJWlDz4lWgviag9aEY1PQIJRozOoXykBzECblYKRqVleHFcfWemo7V6iFsOl8x/ovK9agoh6pn8JfTGqitCNVwdzb5BLYO5/SjFYExAYea1sSuq6XSpprXufklHXEOuaVPWoRCL763T2L4K8VM2fbRWNYX3xoTplWEuGxZOAkp7E5gFsj1tWvBNjlZd+uHxwnE5srtbvRp044KK2sgbmDS7I+ZXDjHAnsGCFb+OXuc3dXfS5wwqo2p6EUvz6ugOI6RuUOcJSGaV8NiVqRodEri8VA0mnfzfj/Z5b1h6naPyGR2tIhIi94pgpv2JPmN1IhEmsKtSfsrR+JKrpzMnk/z5XUQFYiEZ7rNwnKeO7uieGFD7cm7NIo57qoN6Lzfn+SpDErkCiRdAoPtVWbzoG8Ac1VV/MCxuvXTqswvGnElDaA6WMo/AXIJwSQEAT19FKDCbroQXCa6XvQbpROs0hAkes/D+Qd3cyg2vU2olZEqx+w7kmOJQ/FKlFyCwk1BbvxK70/K34UXVRpaU3igVOyYcK4qDT/3RdBPleWIms411cx6pQSNbCcJsxb+lqIWMm8uIP1m08sn1+m11ZgPbq3rGmyAAi4//z0yz5Als=
      app:
        master: system-testing-template
      on:
        repo: sschilbe/SystemTestingTemplate
  - stage: test staging
    install:
    - pip install robotframework
    - pip install --upgrade requests
    - pip install robotframework-selenium2library
    - pip install --upgrade urllib3
    script:
    - robot --variable BROWSER:chrome --variable VERSION:latest --variable PLATFORM:MAC
      test.robot
