dist: xenial
language: python
cache: pip
python:
- 2.7
install:
- pip install -r requirements.txt
script:
- pytest -v
jobs:
  include:
  - stage: deploy to staging
    deploy:
      provider: heroku
      api_key:
        secure: L6HRoui81k0JVdBmsTa+cEAGPqVmXOwuQSwyTLszq6ZGc3qOuTg4sQcxE4TOzd0d2D7rl0I7iB7D0dms1gbevtUHUCd9Q8gwHnGSw235qc4NFqjAF7HU2oK6RrpAOTXwUWlInQnsTzN0eay465Dfrt5/fHONrVV0yKZP6HbGPNGq/iV5hDxZy5E3/S2h0qq5J7CU+OaMYCqeAi3Q44tcS7v3OMguWaMoHLVjaj4nM5aOoogyN7AJ8RMZZ/aX9SFVvmVOooYRe6UO81gogSEnk+tCtG7BO/svIsyUwJK60XxCtV4M7JRJ1MRMEpyDGjvi/UbFJMfBSrFH9Os8xPZAN3rUoCR8+Fn1dLmzPA7kN7R/0pCcO+/g/ilyl1WgpvM5Zv69KgOLGhS+Kxsm74mRkK6gg6+Pw9vA21k1W9FJLt98IbIO82xIgZKEDlv/N7eu6JmhNbyoS2G1sN/vup0y8VVB6d0f92h+nNRKNDUUBncf0dTb8DZiaREf0gGnasyL0qnC6bjH73wgFy07uR6h+2m2ypBvuyuD6x4iecYIXlKQCqcbI2lKgnNX0imV0v9vykeDDOtcg8a+Mkyamt0oyeyzzny9LJyiQhZfdnnxXmcX82Ypk+jOiw+VE9geAgNczF5aBK77Mi+UFdmwDYb1gCm1SW3wZ2ubna0cfwx/Oho=
      app:
        master: system-testing-dev-soc-live
      on:
        repo: sschilbe/DevSocLive
  - stage: test staging
    install:
    - pip install robotframework
    - pip install --upgrade requests
    - pip install robotframework-selenium2library
    - pip install --upgrade urllib3
    script:
    - robot --variable BROWSER:chrome --variable VERSION:latest --variable PLATFORM:MAC
      test.robot
